local icons = {
  vertical_bar = '┃',
  vertical_bar_thin = '│',
  left = '',
  right = '',
  block = '█',
  left_filled = '', right_filled = '',
  slant_left = '',
  slant_left_thin = '',
  slant_right = '',
  slant_right_thin = '',
  slant_left_2 = '',
  slant_left_2_thin = '',
  slant_right_2 = '',
  slant_right_2_thin = '',
  left_rounded = '',
  left_rounded_thin = '',
  right_rounded = '',
  right_rounded_thin = '',
  circle = '●',
  component_separators = { '', '' },
  heart = '',
  heart_outline = '',
  apple = '',
  duck = '',
  ghost = '',
  incognito = '﫸',
  terminal = '',
  right_dragon = '',
  left_dragon = '',
  rhombus = "●"
}

return icons
